### ISSUE TITLE
[BUG] Breaks module QuickSceneView

### ISSUE THREAD

**Issue by acd-jake** [Forien/foundryvtt-forien-scene-navigator#1]
**Module Version:** v0.1.4

**Describe the bug**
After activation of the scene navigator the scene directory context menu entry "View" added by the module QuickSceneView is no longer visible. After disactivation of the scene navigator the context menu is shown again.

**Expected behavior**
The context menu entry for the QuickSceneView is still available when the scene navigator module is activated.

**Browser:**
 - 

**Foundry Version:** 
Version 0.6.5
**Game System:** 
Dungeons &Dragons 5th Edition 0.93

**Additional context**
QuickSceneView (https://gitlab.com/reichler/quicksceneview) Version 0.2

**Comment by Forien** [comment]
That is weird, it shouldn't interact in any way. I will test.

**Comment by Forien** [comment]
Confirmed, QuickSceneView was using Hook, which my module "broke" by extending the `SceneDirectory` class.

Fixed in v0.1.5
