### ISSUE TITLE
holding Ctrl or Alt doesn't work for Mac

### ISSUE THREAD

**Issue by ColombianJulio** [Forien/foundryvtt-forien-scene-navigator#2]
Not sure if application of the module works differently on Macs but the Ctrl and Alt buttons don't work when dragging and dropping unto a journal entry.

Normal
![normal](https://user-images.githubusercontent.com/67991100/86934102-4aadec00-c109-11ea-8c15-20c51e0d883b.gif)

holding ctrl
![ctrl](https://user-images.githubusercontent.com/67991100/86934142-58fc0800-c109-11ea-8823-29e76a73af55.gif)

holding Alt
![alt](https://user-images.githubusercontent.com/67991100/86934169-61544300-c109-11ea-9ef4-3243429f91a7.gif)

**Comment by Forien** [comment]
I don't own any device with Mac, so it's hard for me to debug. And my knowledge about Mac is close to zero. 

Can you check console for any errors? (on Windows Chrome it would be F12).

Also what browser are you using? Have you tried `⌘` key instead of Control?

**Comment by Forien** [comment]
Updated to v0.1.6:

1. `Alt` tested and works
1. Added support for `Command` on macOS. Though it is required to "release" command button before dropping link onto text editor.

Closing the issue, unless problem persists, in which case please provide additional information (like used browser etc).

**Comment by ColombianJulio** [comment]
Whih browser? im using the application on my desktop foundry vtt. theres no internet browser if thats what youre asking

**Comment by ColombianJulio** [comment]
here is an on sreen keyboard showing it isnt working.

![problem](https://user-images.githubusercontent.com/67991100/86954009-4c84a900-c123-11ea-86b8-e73429ec2e18.gif)
