### ISSUE TITLE
functions not working on mac. no internet browser, just on foundry vtt

### ISSUE THREAD

**Issue by ColombianJulio** [Forien/foundryvtt-forien-scene-navigator#3]
on screen keyboard showing functions not working.

![problem](https://user-images.githubusercontent.com/67991100/86954218-979ebc00-c123-11ea-816a-f94e90c70865.gif)

**Comment by Forien** [comment]
Voldemalort on Discord tested it for me and he confirmed that on macOS:

1. Alt works
1. Command works

Although you need to make sure to release key BEFORE you release mouse.
So: hold Alt/Command -> press mouse button -> release key -> drag link onto journal -> release mouse button

Also make sure you are updated to v0.1.6

**Comment by pesky-wobbit** [comment]
It worked for me on macOS as well. I failed several times, though, before following the specific instructions above. I also had to restart Foundry once when I couldn't get the Journal window to close.

**Comment by Forien** [comment]
> It worked for me on macOS as well. I failed several times, though, before following the specific instructions above. I also had to restart Foundry once when I couldn't get the Journal window to close.

next time you will encounter issue that you can't close/save journal entry after dragging scene, please take a look into Console (F12) and see if there is any error. If there is, please inform me (you can create new issue for that)

**Comment by pesky-wobbit** [comment]
will do!

**Comment by ColombianJulio** [comment]
Oh wow it does work! But it’s very precise. 

Julio Ortiz-Forero
